[general]
email = "mass2blast@gmail.com"

[openai]
OPENAI_API_KEY = "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"
